### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by bc129697** [NVlabs/InstantSplat#10]
![image](https://github.com/user-attachments/assets/02fb0467-35bf-4606-8b22-1fe317138d02)

When i run with "bash scripts/run_train_infer.sh" ，This error will occur when using 60 frames of images, but it will not occur when using 25 frames of images

**Comment by kairunwen** [comment]
Hi, the OOM problem is caused by the memory limitations of DUSt3R: [https://github.com/naver/dust3r/issues/1](url), which should be solved by InstantSplat_MASt3R.

You can modify these parameters to reduce GPU memory usage and accelerate model training, but the model performance will be slightly degraded: [https://github.com/NVlabs/InstantSplat/blob/main/coarse_init_infer.py#L70](url)
(1) scene_graph='complete' --> scene_graph='swin'
(2) symmetrize=True --> symmetrize=False

**Comment by alpergel** [comment]
Hi, where can we find InstantSplat_MAST3R?

**Comment by zhiwenfan** [comment]
We are cleaning it and will release the support for MASt3R, 2DGS very soon. Thanks.

**Comment by omaralvarez** [comment]
> We are cleaning it and will release the support for MASt3R, 2DGS very soon. Thanks.

Was this finally implemented or it is never going to be added?

**Comment by kairunwen** [comment]
@omaralvarez We’ve added it to the instantsplat-2dgs branch.
