### ISSUE TITLE
Question about code 

### ISSUE THREAD

**Issue by Gynjn** [NVlabs/InstantSplat#18]
First, thanks for sharing your great work.

BTW, can you elaborate more details in 

`'p_view.z <= 0.2f' -> 'p_view.z <= 0.001f' # line 154`

in environment setup?

Thanks in advance.

**Comment by kairunwen** [comment]
Hi, when rendering images for certain scenes, we obtained the following result using the VanillaGS parameter (i.e., "p_view.z <= 0.2f").

![image](https://github.com/user-attachments/assets/47003879-015c-4aa4-8a07-e4e4cdf8d867)

The issue arises because the point cloud generated by dust3r is too small in scale, and VanillaGS removes Gaussians that are too close to the camera. You can find more details here: [https://github.com/graphdeco-inria/gaussian-splatting/issues/963](url).

**Comment by Six-Bit-007** [comment]
Thank you for this, have been debugging this for hours. Perhaps it would be best if you could note this in the README.
