### ISSUE TITLE
ATE results look weird。

### ISSUE THREAD

**Issue by Yuhuoo** [NVlabs/InstantSplat#3]
Without modifying any code, why is the result of the camera pose like this?

<img width="1333" alt="image" src="https://github.com/user-attachments/assets/5a504a0e-ca10-421f-9c9a-6e0524ec6ab5">

**Comment by murmurelo111** [comment]
Hello, I encountered the same issue. Have you found a solution? Could we exchange contact information to discuss it further?

**Comment by sadra-safa** [comment]
Hi, if you add 
`colmap_cam_extrinsics = {k: v for k, v in sorted(colmap_cam_extrinsics.items(), key=lambda item: item[1].name)}`
after this line https://github.com/NVlabs/InstantSplat/blob/2c5006d41894d06464da53d5495300860f432872/metrics.py#L47 it should work as expected.
![pose_vis](https://github.com/user-attachments/assets/a8d35760-11e6-4d60-a3b1-00fa92694fca)

The reason is that the pose evaluation code assumes that the gt poses are sorted according to the image names. However, the `read_colmap_gt_pose` function reads the extrinsics based on the IMAGE_IDs of colmap in `images.bin`. But these colmap IDs are not necessarily sorted based on image names. The above line sorts the dictionary based on the image names.

**Comment by murmurelo111** [comment]
Thanks!!

**Comment by anvenle** [comment]
i added above line https://github.com/NVlabs/InstantSplat/issues/3#issuecomment-2286645047  ,and  found this 
![Screenshot from 2024-08-22 16-18-57](https://github.com/user-attachments/assets/63f1295d-e0ef-46ba-9447-d914e5e49670)
